[default]
dir = "~/dev/github.com/futsuuu/dot/dot"
sync_type."sys(os)" = { default = "symlink", windows = "junction" }

[[dotfiles]]
path = "sinc"
target = "~/.config/sinc"

[[dotfiles]]
path = "glazeWM"
enable."sys(os)" = { default = false, windows = true }
target = "~/.glaze-wm"

[[dotfiles]]
path = "hyprland"
target = "~/.config/hypr"
enable."sys(os)" = { default = false, "arch linux" = true }

[[dotfiles]]
path = "waybar"
target = "~/.config/waybar"
enable."sys(os)" = { default = false, "arch linux" = true }

[[dotfiles]]
path = "neovim"
  [dotfiles.target."sys(os)"]
  default = "~/.config/nvim"
  windows = "~/AppData/Local/nvim"

[[dotfiles]]
path = "alacritty"
  [dotfiles.target."sys(os)"]
  default = "~/.config/alacritty"
  windows = "~/AppData/Roaming/alacritty"

[[dotfiles]]
path = "tmux.conf"
target = "~/.tmux.conf"
enable."which(tmux)" = { default = true, "" = false }

[[dotfiles]]
path = "tig"
target = "~/.config/tig"

[[dotfiles]]
path = ".gitconfig"
target = "~/.gitconfig"
sync_type."sys(os)" = { default = "symlink", windows = "hardlink" }

[[dotfiles]]
path = "curlrc"
target = "~/.curlrc"
sync_type."sys(os)" = { default = "symlink", windows = "hardlink" }

[[dotfiles]]
path = "bat"
  [dotfiles.target."sys(os)"]
  default = "~/.config/bat"
  windows = "~/AppData/Roaming/bat"

[[dotfiles]]
path = "neofetch"
target = "~/.config/neofetch"

[[dotfiles]]
path = "wofi"
target = "~/.config/wofi"
enable."sys(os)" = { default = false, "arch linux" = true }

[[dotfiles]]
path = "chromium-flags.conf"
target = "~/.config/electron-flags.conf"
enable."sys(os)" = { default = false, "arch linux" = true }

[[dotfiles]]
path = "chromium-flags.conf"
target = "~/.config/vivaldi-stable.conf"
enable."sys(os)" = { default = false, "arch linux" = true }
