[default]
dir = "~/dev/github.com/futsuuu/dot/dot"
sync_type."match(os)" = { default = "symlink", windows = "junction" }

[[dotfiles]]
path = "sinc"
target = "~/.config/sinc"

[[dotfiles]]
path = "glaze-wm"
enable."match(os)" = { default = false, windows = true }
target = "~/.glaze-wm"

[[dotfiles]]
path = ".gitconfig"
target = "~/.gitconfig"
sync_type."match(os)".windows = "hardlink"

[[dotfiles]]
path = "bat"
  [dotfiles.target."match(os)"]
  default = "~/.config/bat"
  windows = "~/AppData/Roaming/bat"

[[dotfiles]]
path = "neofetch"
target = "~/.config/neofetch"
