[default]
dir = "~/dev/github.com/futsuuu/dot/dot"
sync_type."sys(os)" = { default = "symlink", windows = "junction" }

[[dotfiles]]
path = "sinc"
target = "~/.config/sinc"

[[dotfiles]]
path = "paru"
target = "~/.config/paru"
enable."sys(os)" = { default = false, "arch linux" = true }

[[dotfiles]]
path = "xremap"
target = "~/.config/xremap"
enable."which(xremap)" = { default = true, "" = false }

[[dotfiles]]
path = "hyprland"
target = "~/.config/hypr"
enable."sys(os)" = { default = false, "arch linux" = true }

[[dotfiles]]
path = "waybar"
target = "~/.config/waybar"
enable."which(waybar)" = { default = true, "" = false }

[[dotfiles]]
path = "eww"
target = "~/.config/eww"
enable."which(eww)" = { default = true, "" = false }
hook_add = "cargo build"

[[dotfiles]]
path = "dunst"
target = "~/.config/dunst"
enable."sys(os)" = { default = false, "arch linux" = true }

[[dotfiles]]
path = "neovim"
  [dotfiles.target."sys(os)"]
  default = "~/.config/nvim"
  windows = "~/AppData/Local/nvim"

[[dotfiles]]
path = "goneovim"
target = "~/.config/goneovim"
enable."which(goneovim)" = { default = true, "" = false }

[[dotfiles]]
path = "profile.png"
target = "~/.face.icon"
enable."which(sddm)" = { default = true, "" = false }

[[dotfiles]]
path = "alacritty"
  [dotfiles.target."sys(os)"]
  default = "~/.config/alacritty"
  windows = "~/AppData/Roaming/alacritty"

[[dotfiles]]
path = "tmux.conf"
target = "~/.tmux.conf"
enable."which(tmux)" = { default = true, "" = false }

[[dotfiles]]
path = "tig"
target = "~/.config/tig"

[[dotfiles]]
path = "lazygit"
  [dotfiles.target."sys(os)"]
  default = "~/.config/lazygit"
  windows = "~/AppData/Roaming/lazygit"

[[dotfiles]]
path = ".gitconfig"
target = "~/.gitconfig"
sync_type."sys(os)" = { default = "symlink", windows = "hardlink" }

[[dotfiles]]
path = "curlrc"
target = "~/.curlrc"
sync_type."sys(os)" = { default = "symlink", windows = "hardlink" }

[[dotfiles]]
path = "nushell"
  [dotfiles.target."sys(os)"]
  default = "~/.config/nushell"
  windows = "~/AppData/Roaming/nushell"

[[dotfiles]]
path = "neofetch"
target = "~/.config/neofetch"

[[dotfiles]]
path = "wofi"
target = "~/.config/wofi"
enable."sys(os)" = { default = false, "arch linux" = true }
