name: Release-smpt

on: [push]

env:
  CARGO_TERM_COLOR: always
  PACKAGE_DIR: smpt
  PACKAGE_NAME: smpt

jobs:
  build:
    name: Build smpt
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-musl
          - x86_64-pc-windows-msvc
          - x86_64-apple-darwin
        include:
          - target: x86_64-unknown-linux-musl
            os: ubuntu-latest
          - target: x86_64-pc-windows-msvc
            os: windows-latest
          - target: x86_64-apple-darwin
            os: macos-latest

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ./${{ env.PACKAGE_DIR }}/target
          key: ${{ runner.os }}-cargo-${{ hashFiles(format('{0}/Cargo.lock', env.PACKAGE_DIR)) }}

      - name: Setup Rust toolchain
        run: |
          rustup target add ${{ matrix.target }}

      - name: Compile
        run: |
          cd ${{ env.PACKAGE_DIR }}
          cargo build --verbose --release --target=${{ matrix.target }}
        
      - name: Convert to zip
        if: matrix.target != 'x86_64-pc-windows-msvc'
        run: |
          sudo mv ./${{ env.PACKAGE_DIR }}/target/${{ matrix.target }}/release/${{ env.PACKAGE_NAME }} ./${{ env.PACKAGE_NAME }}
          zip ./release.zip ./${{ env.PACKAGE_NAME }}

      - name: Convert to zip (windows)
        if: matrix.target == 'x86_64-pc-windows-msvc'
        shell: powershell
        run: |
          Move-Item ./${{ env.PACKAGE_DIR }}/target/${{ matrix.target }}/release/${{ env.PACKAGE_NAME }}.exe ./${{ env.PACKAGE_NAME }}.exe
          Compress-Archive -Path ./${{ env.PACKAGE_NAME }}.exe -DestinationPath ./release.zip

      - name: Save a release
        uses: actions/upload-artifact@v3
        with:
          name: release-${{ matrix.target }}
          path: ./release.zip

  publish:
    name: publish
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: release-x86_64-unknown-linux-musl
          path: ${{ env.PACKAGE_NAME }}-x86_64-unknown-linux-musl
      - uses: actions/download-artifact@v3
        with:
          name: release-x86_64-apple-darwin
          path: ${{ env.PACKAGE_NAME }}-x86_64-apple-darwin
      - uses: actions/download-artifact@v3
        with:
          name: release-x86_64-pc-windows-msvc
          path: ${{ env.PACKAGE_NAME }}-x86_64-pc-windows-msvc

      - run: ls -al

      - name: Move files
        run: |
          for release_dir in * ;do
          mv ${release_dir}/release.zip ./${release_dir}.zip
          done

      - run: ls -al

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: "*.zip"
          name: ${{ env.TAG }}
          token: ${{ secrets.GITHUB_TOKEN }}
